# Generated by Django 6.0 on 2026-03-24 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_theme_product_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='theme',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
